### ISSUE TITLE
Appreciation to all of you & Advice about project name

### ISSUE THREAD

**Issue by Retia-Adolf** [minetest/contentdb#106]
Firstly let me appreciate you for your STUNNING FREE Licensed works here!

I actually found this game when just start to explore the world of free gaming, hadn't fancying there were quality games to enjoy as in proprietary world though.

In fact I didn't look forward to that there were well-built Eco to enjoy without taking patient with and participating in it when got started into free software, so not to mention free gaming.

But here is this amazing game brings the idea of Minecraft to the free world! Thank you so much for your great work, thank you for making my journey to the free gaming world being promising now!!

Then I have some advice about this project name `contentdb`.

I'd suggest to use `craftdb`, `worksdb` or noticeably `minetestdb`, instead of this one. The reason is it's [advised by FSF](https://www.gnu.org/philosophy/words-to-avoid.html#Content) as following quoted:

>  If you want to describe a feeling of comfort and satisfaction, by all means say you are “content,” but using the word as a noun to describe publications and works of authorship adopts an attitude you might ***rather avoid: it treats them as a commodity whose purpose is to fill a box and make money. In effect, it disparages the works themselves.*** If you don't agree with that attitude, you can call them “works” or “publications.”
> 
> ***Those who use the term “content” are often the publishers that push for increased copyright power in the name of the authors (“creators,” as they say) of the works.*** The term “content” reveals their real attitude towards these works and their authors. This was also recognized by Tom Chatfield in the Guardian:
> 
>> Content itself is beside the point—as the very use of words like content suggests. The moment you start labelling every single piece of writing in the world “content,” you have conceded its interchangeability: its primary purpose as mere grist to the metrical mill. 
> 
> In other words, “content” reduces publications and writings to a sort of pap fit to be piped through the “tubes” of the internet. 

I know maybe it could be a little annoying for FSF-supporters to advocate their choice of words everywhere, but I believe you who generously release all of your works under LGPL, GPL and CC-BY-SA etc. will understand and welcome those actions we take.

Most of the time we're just got used to those buzzwords spreaded by some unexplainable overwhelming trends. But they are popluar doesn't necessarily mean they make any actual sense for us. From this point of view, I agree with what FSF has satirized on them:

> The term “content management” takes the prize for vacuity. “Content” means “some sort of information,” and “management” in this context means “doing something with it.” So a “content management system” is a system for doing something to some sort of information. Nearly all programs fit that description.

Honestly the word "content" seems to be clear merely within bussiness realm, so throwing it away will only refresh our computing world with no harm. :) Hope you could adopt this advice. Thank you very much, here from Retia.

**Comment by tukkek** [comment]
This is not your personal blog, this is an issue tracker for technical issues and planning for Minetest. I believe everyone involved appreciates your cheers and praises but you should post this to social media or to a game review website, not to GitHub.

**Comment by Retia-Adolf** [comment]
@tukkek You are right, I apologize. Maybe I'm too verbose, I mainly want to talk about the issue, though not technical one.

**Comment by Linuxdirk** [comment]
>>Those who use the term “content” are often the publishers that push for increased copyright power in the name of the authors (“creators,” as they say) of the works.

So you want to let them win by defining the term "content"?

I'd say: use the terms "content" and "creators" whenever it comes to free software. Now more than ever. Don't let commercial publishers put their copyright label on terms that describe things very well.

... and why the hell is this even an issue that is still open?
