### ISSUE TITLE
VCS release creation fails for cgit repositories

### ISSUE THREAD

**Issue by orwell96** [minetest/contentdb#108]
Task Failed

'\nfatal: unable to update url base from redirection:\n  asked for: http://:@git.bananach.space/advtrains.git/info/refs?service=git-upload-pack\n   redirect: https://git.bananach.space/cgit.cgi?url=advtrains.git/info/refs&service=git-upload-pack\n'

**Comment by rubenwardy** [comment]
What URL did you give originally?

**Comment by orwell96** [comment]
As VCS Repository is entered:
https://git.bananach.space/advtrains.git/

**Comment by sofar** [comment]
Try finding out if you can use a git:// or git@ url instead. HTTPS can redirect, and this is likely the cause. It's potentially fixable, but, I'm not sure if @rubenwardy wants to do this, since there are security concerns about accepting redirects.

**Comment by orwell96** [comment]
ok, I'll try this

**Comment by rubenwardy** [comment]
```
rubenwardy:/tmp $ git clone git.bananach.space/advtrains.git
fatal: repository 'git.bananach.space/advtrains.git' does not exist
```

**Comment by rubenwardy** [comment]
this should be fixed
