### ISSUE TITLE
Remove broken games before MT 5.0.0 release

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/contentdb#119]
Hello, this is a request to remove from public view the critically broken or seriously buggy things before the MT 5.0.0 release.

The definition of “critically broken or seriously buggy” is met when one of the following things is true:

* The thing doesn't work at all / doesn't start up
* The chat is flooded with Lua errors
* Crash that is easy to trigger
* Game-breaking bug
* The graphics or sounds are completely screwed up

This is also a request to establish a bare minimum quality standard, which should basically say “if it's broken, it will be hidden/removed/disabled until you fix it”. So that broken crap doesn't drag the overall quality down. When in doubt, remove.
It seems that all games currently on the Content DB are broken or have a serious bug, most likely due to breaking 5.0.0 changes which could not be avoided.
Maybe you should be generally more careful in allowing games to be added in the first place, especially when the author has NOT made the game 5.0.0-ready.
Note that game authors almost certainly have to make extra work to make the game 5.0.0-ready, because of the common “player model is shifted into the ground” problem that was a breaking change in 5.0.0-dev and requires manual intervention from the game author.

I suggest a simple process to clean the Content DB of broken garbage:
1) Anyone w/ account can report a game or mod (or any thing) as broken. The reporter must be prepared to write a reproducible bug report, or link to an existing one
2) Someone needs to check this claim
3) If verified, the thing is hidden, only visible to the author, and the author is notified
4) If the author wants the thing to re-appear, they must upload a fixed version or show why the claim of brokenness is false
5) After verification, the thing is “unlocked” again

If this process is too complex, I suggest a simpler one-time process:
Remove/hide all games from the Content DB for now until it has been proven that the games are NOT broken.

Note that my own games will be affected by this request, too. All of my games will (kinda) break, too, so they must be disabled. My plan was to do the neccessary 5.0.0 fixes to the games after MT 5.0.0 is out (not before). I never asked for my games to be added to Content DB anyway, and this is exactly the reason why.

**Comment by Wuzzy2** [comment]
Min versions might work.

But I doubt that max version will work. Given that version numbers are determined by gut feeling (whenever the devs “feel like” releasing a major version), rather than strict rules, they are hardly predictable. Also, I can impossibly predict that my game will break in version 7.4.19 anyway.

As for mods. Maybe extreme measure, but I think the safest way would be “guilty (of breakage) until proven otherwise”. :D I.e. assume everything is broken before it at least survived a superficial test (i.e. no insta-crash, no Lua error spam, no packaging fail, bad license, etc.). It was not a good idea to open the floodgates for untested code in the first place. Call me paranoid, but it will make Minetest show in a really bad light if MT 5.0.0 will release with hundreds of broken mods.
Heck, even my HUD Bars mod will break. :( I think there will be a lot of work for me after release, but I am prepared to do it.
Tagging as “works for 5.0.0” sounds pointless, since Content DB first appears in 5.0.0. Mods that don't work in 5.0.0 should have never been added in the first place. :( Or did you mean it as a quick and dirty hack to save some time? :)

The only things that should be relatively safe are texture packs IMO.

As for communication, you could simply use e-mail. Why? Because it works. Don't re-invent the wheel. Don't re-invent phpBB. You will waste your time.

**Comment by rubenwardy** [comment]
Threads are needed to be able to add notes to packages as part of the review process. Without threads, multiple editors could end up tripping over themselves

**Comment by Wuzzy2** [comment]
Oh, OK. Nvm.

**Comment by rubenwardy** [comment]
This is now donw
