### ISSUE TITLE
Show “non-free” warning on preview list not just when hovering

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/contentdb#120]
In the content DB website, if you hover a thing/screenshot in the list of things, the “non-free” warning might pop up. But if you move the mouse away, the warning disappears.

It would be more logical IMO to show the “non-free” warning all the time, i.e. not only while hovering it.

**Comment by rubenwardy** [comment]
I did it like this to avoid drawing attention to the non-free stuff. A better approach would probably be a greyed out icon or text in the top right when not hooving
