### ISSUE TITLE
[Discuss] Hide non-free content by default?

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/contentdb#121]
This is more about consistency. In Minetest, non-free things are now hidden by default, but this is not the case for the website, which shows all things by default, and it seems there is also no filtering option.

So I suggest to add at least such a filtering option to match the functionality of Minetest.

Agree? Disagree?

**Comment by rubenwardy** [comment]
As for the hiding by default, I don't care much in either direction, and would learn towards doing this.

As for the filtering option, this should probably be done using a combination of cookies and user account settings, to allow anonymous users to opt-in to the content
