### ISSUE TITLE
Package "provides" and "dependencies" listing out of date.

### ISSUE THREAD

**Issue by Warr1024** [minetest/contentdb#127]
Creating a new release does not update the list of mods in the "provides" list in CDB on the details page sidebar (and possibly other places that use the same data).  It seems that this information gets baked in e.g. when creating the package, but CDB doesn't detect additions in subsequent releases.

For example, CDB lists only 13 mods at https://content.minetest.net/packages/Warr1024/nodecore/, but the latest release has 17.

**Comment by bell07** [comment]
+1 I need this feature too to keep the provides "whynot" list up to date with currently 157 mods
