### ISSUE TITLE
Content DB doesn't support commits from non-master branch

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/contentdb#130]
When I tried to upload MineClone 0.50.2, I had several errors. I tried to choose the commit ID, the 0.50.2 tag and the 0.50 branch. Nothing worked.
The relevant commit is in the 0.50 branch, NOT in master. Maybe that's the reason.
I had multiple players complaining about a broken download and they were correct.

After I released 0.51.0, which is on the master branch, Content DB was happy again.

**Comment by Wuzzy2** [comment]
To clarify, I get “server error” so the bug is definitely on your side, not on my side.

**Comment by rubenwardy** [comment]
The error is 

> gitdb.exc.BadName: Ref '0.50' did not resolve to an object

**Comment by Wuzzy2** [comment]
Well, the 0.50 is a branch, while 0.50.0, 0.50.1, 0.50.2 are tags.
If it fails on any on these, it's a bug cuz Content DB claims it works on branches and tags.

> The worker page whitelists exceptions to show, and it turns out that the missing reference error is not the same as the clone/etc error

So it's an errornous error message? XD
