### ISSUE TITLE
Verification token does not work

### ISSUE THREAD

**Issue by nekoswag** [minetest/contentdb#132]
https://content.minetest.net/user/claim/
Option 2 (verification token) doesn't work at the moment. When filling in the user name and clicking 'next', an error page is shown:

> Oops! Something went wrong
> We seem to be having technical difficulties.
> Please try again in a while, and report the issue if it persists.

**Comment by rubenwardy** [comment]
The error is:

> users.py, line 269, in user_claim_page if token in sig: TypeError: argument of type 'NoneType' is not iterable

Did you enter your forums username correctly?

**Comment by nekoswag** [comment]
yes

**Comment by nekoswag** [comment]
it works now, I didn't know that you had to set the code in the signature beforehand and thought it would be checked manually.
