### ISSUE TITLE
Allow NSFW content

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/contentdb#137]
Please allow NSFW content. Thank you.

**Comment by rubenwardy** [comment]
I do not want to moderate any sexual content

**Comment by sofar** [comment]
>I do not want to moderate any sexual content

Yeah, that's a PTSD inducing nightmare.

Please reject this.

**Comment by Linuxdirk** [comment]
> Please reject this.

Yeah, maybe add some guns mods instead.

**Comment by Wuzzy2** [comment]
I think you should be more specific about what you actually want. About what is OK and what not. Otherwise I think it is futile to discuss further.

For instance, if you're against “violence” without further qualification, then you can ban pretty much everything, including MTG because of swords and PvP. I don't think this is the goal. ;-) Therefore I insist on being specific.
