### ISSUE TITLE
Unfair punishment of screenshot-less mods

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/contentdb#138]
I'm not sure, but it seems that mods without a screenshot are punished. In 99% of cases this makes sense.

However, there are some mods which simply cannot have any screenshot, i.e. if they are just a pure API mod or just add an invisible gameplay mechanic.

It seems unfair to punish those as well. I have no good idea on how to tackle this, but I think it's still a (minor) issue.

**Comment by Linuxdirk** [comment]
>  I have no good idea on how to tackle this

Maybe do not punish mods for not having a screenshot when they have the "API / Library / Programmer Tools" tag set. In the meantime just add a random image as screenshot (did the same for one of my mods).

**Comment by rubenwardy** [comment]
fixed
