### ISSUE TITLE
How the "Top Mods" / "Top Games" are selected for the main page?

### ISSUE THREAD

**Issue by bell07** [minetest/contentdb#141]
Previously the question: How the "Top Mods" / "Top Games" are selected for the main page?

My assumption is the selection is based on downloads count, but lord-of-the-test (228 downloads) and Pixture (191) are not the most-downloaded games.
We have Minetest Game (602 Downloads), Whynot (596 Downloads) and other games above 300 Downloads that could be "Top games 3 and 4").

**Comment by rubenwardy** [comment]
```py
def recalcScore(self):
	self.score = 10

	if self.forums is not None:
		topic = ForumTopic.query.get(self.forums)
		if topic:
			days   = (datetime.datetime.now() - topic.created_at).days
			months = days / 30
			years  = days / 365
			self.score = topic.views / max(years, 0.0416) + 80*min(max(months, 0.5), 6)

	if self.getMainScreenshotURL() is None:
		self.score *= 0.8

	if not self.license.is_foss or not self.media_license.is_foss:
		self.score *= 0.1
```

**Comment by rubenwardy** [comment]
New issue: #154
