### ISSUE TITLE
[wiki] Build instructions are broken for windows 10

### ISSUE THREAD

**Issue by b3u** [minetest/contentdb#142]
Both of the build instructions didn't work for me on windows 10

I get the following error with the **simple dev server method** while trying to run `python setup.py -t`:
https://gist.github.com/b3u/7364c585b3e368c325af2011592d16dd

For the **docker build method**, It seems that one needs either windows pro or enterprise edition to run docker.

**Comment by rubenwardy** [comment]
I don't have the ability to provide assistance for Windows 10

**Comment by Calinou** [comment]
> For the docker build method, It seems that one needs either windows pro or enterprise edition to run docker.

You can use [Docker Machine](https://docs.docker.com/machine/overview/) to run a virtual machine that will run Docker containers on Linux. This can be done on any Windows version starting from Windows 7.

**Comment by b3u** [comment]
I'm not interested in this PR anymore. Feel free to close.
