### ISSUE TITLE
Skins

### ISSUE THREAD

**Issue by b3u** [minetest/contentdb#143]
Can we have a skins section (like the mods, games, textures, etc)? Even though Minetest Game itself doesn't support custom skins, the minetest lua api does, and many games do.

I envision that this would need more thought, but some distinction should be made between clothes and armor, between full-body and sectioned outfits, and maybe between v1.0 and v1.8 skins.

I think that it is important to have a central hub for finding skins, as there are many for minecraft.

**Comment by rubenwardy** [comment]
There is no standard location for installing skins, and ContentDB aims to only contain things that can be installed

See http://minetest.fensta.bplaced.net/
