### ISSUE TITLE
"New Thread": Broken link to issue tracker

### ISSUE THREAD

**Issue by ClobberXD** [minetest/contentdb#147]
See https://content.minetest.net/threads/new/?pid=29 for example. The yellow box contains a link which should point to the package's issue tracker, but points to the same "New Thread" page instead.

**Comment by rubenwardy** [comment]
What yellow box?

**Comment by ClobberXD** [comment]
Did you checkout the link in my previous post? The one that says, "Found a bug? ..."

![Screenshot from 2019-05-02 14-21-02](https://user-images.githubusercontent.com/36130650/57064999-abf85500-6ce5-11e9-945d-ac652617862d.png)

**Comment by rubenwardy** [comment]
Oh, that doesn't appear to moderators
