### ISSUE TITLE
Removing one tag removes all tags

### ISSUE THREAD

**Issue by ClobberXD** [minetest/contentdb#148]
#### Steps to reproduce

- Create a new package (optional).
- Add more than one tag.
- Remove any one tag.
- Notice all the other tags are removed as well.

**Comment by rubenwardy** [comment]
I can't reproduce this. Try ctrl+alt+r?

**Comment by ClobberXD** [comment]
`Ctrl + Alt + R` doesn't seem to do anything for me. What does it do?

Btw, I noticed something else - only the tags that were added in the current edit session are removed. So if I edit an existing package, and follow the steps to reproduce in the first post, only the newly added tags are deleted, and the old ones remain intact.
