### ISSUE TITLE
Add full REST API

### ISSUE THREAD

**Issue by rubenwardy** [minetest/contentdb#157]
**Include:**

- [x] Create releases
- [x] Update package meta
- [x] Create/edit/delete screenshots

**Don't include:**

* Create package, comments, threads
* Sign up
* Update profile/etc

@Warr1024

**Comment by thomasrudin** [comment]
> Create releases

:+1: for that, i like to use that with github actions to create an end-to-end release pipeline:
* git tag
* github actions: luacheck
* github actions: push to contentdb

**Comment by rubenwardy** [comment]
CDB now has support for creating access tokens. Creating releases is next up on my to-do list, I'll also provide an example config for creating releases from GitHub actions

**Comment by rubenwardy** [comment]
The ability to create releases has been here for a few months

**Comment by rubenwardy** [comment]
Marked as beginner-friendly, as doing _parts_ of this issue is

**Comment by rubenwardy** [comment]
Implemented
