### ISSUE TITLE
Please add Handle_Schematics to the content database

### ISSUE THREAD

**Issue by CHJ85** [minetest/contentdb#164]
Hi there.
A few mods in the database require the Handle_Schematics mod.
One one them being Basic_Houses.
So could you please add it to the database.
https://forum.minetest.net/viewtopic.php?f=9&t=13116.

**Comment by sofar** [comment]
@sokomine needs to do that, nothing core devs should be forced to do

**Comment by CHJ85** [comment]
Oh. I didn't know that was something the dev themselves could do.

**Comment by rubenwardy** [comment]
Done
