### ISSUE TITLE
Sort depends/provides lists on web UI

### ISSUE THREAD

**Issue by Warr1024** [minetest/contentdb#169]
What it says on the tin.

For example, on https://content.minetest.net/packages/Warr1024/nodecore/ the "provides" list on the right sidebar is not sorted, so it's much harder than necessary to manually check to see if an expected item is in that list or not.

As a general rule, if there is no particular meaning to the order of some set (as is the case for depends/provides lists) then they might as well be given some order.  Lexical ordering seems good enough.

**Comment by rubenwardy** [comment]
5fa0a7866a53624e65866ec261a4bb7b77d45ef8 7ac7af477403f67e75018d77901ddf45a9457805
