### ISSUE TITLE
Delegate credentials for package deployment

### ISSUE THREAD

**Issue by Warr1024** [minetest/contentdb#171]
As a publisher of multiple packages, I'd like to setup CI/CD systems to automatically deploy releases for some of my packages.  I already have a system for scripting deployments via CDB.  However, I don't want to share my account password (which has access to ALL my packages) with this system.  I would rather be able to create a separate login credential (i.e. separate password, and possibly a separate or derived username) that only has permissions to request new releases for one specific package.

**Comment by rubenwardy** [comment]
I'm planning to have access tokens for stuff like this, being able to limit to a particular package is a great idea

**Comment by rubenwardy** [comment]
Done
