### ISSUE TITLE
Ranking

### ISSUE THREAD

**Issue by Extex101** [minetest/contentdb#172]
There needs to be a mod rank
In mod information have a number displaying how many mods down the mod is in the top mods list
For example technic would say 1, mesecons would say 2, 3d_armor would be 10

**Comment by Extex101** [comment]
Why did you close it?

**Comment by rubenwardy** [comment]
The package scoring mechanism is automated and inherently biased. It shouldn't be taken to be a ranking of the best mods, so displaying it as such would be inappropriate

**Comment by rubenwardy** [comment]
I'm concerned that adding such a field would cause users to think that it's an actual ranking of mods, rather than just a representation of what is currently popular, and would also incentivise cheating the system

**Comment by rubenwardy** [comment]
I'll keep this open for a bit to gather opinions, it was rude to close it so quickly

**Comment by appgurueu** [comment]
> The package scoring mechanism is automated and inherently biased. It shouldn't be taken to be a ranking of the best mods, so displaying it as such would be inappropriate
That. So a :-1: from me.

**Comment by Extex101** [comment]
Yeah I just want to know how high my mod is.
Even like a 900 would be good XD

**Comment by rubenwardy** [comment]
>  Even like a 900 would be good XD

I can tell you that it's definitely less than 900

**Comment by sofar** [comment]
I'm not saying that there should be no ranking, but, unless you have several metrics that you can rank mods from, it would be very difficult to bring a reliable and useful ranking method, and it will be very much prone to manipulation.

Since you don't have any real usage data at all, and only indirect ones, I feel it's better to not do any ranking.

**Comment by Extex101** [comment]
Maybe have a "filter" dropdown containing: 
▪ Downloads, 
▪ Forum views
▪ ect
