### ISSUE TITLE
Random order ("explore")

### ISSUE THREAD

**Issue by appgurueu** [minetest/contentdb#174]
An option to explore packages in (almost) random order, to give less popular packages a shot. Also a feature that was implemented in UnCDB.

**Comment by rubenwardy** [comment]
The problem is maintaining the random order when using pagination. If you don't care about pagination, then this feature is as simple as changing this line:

https://github.com/minetest/contentdb/blob/master/app/querybuilder.py#L28

**Comment by rubenwardy** [comment]
https://github.com/minetest/contentdb/commit/94426e97aa0f539be2c0a04b91e1beefef30563e

**Comment by rubenwardy** [comment]
When this change is deployed, you'll be able to view packages in random order using the `random=1` parameter to the query string.

Eg: https://content.minetest.net/packages/?random=1
