### ISSUE TITLE
Is the 20 character technical name limit a "hard" one?

### ISSUE THREAD

**Issue by FaceDeer** [minetest/contentdb#185]
## Summary

I just created a content DB listing for https://github.com/minetest-mods/commoditymarket_fantasy and the content DB rejected the technical name "commoditymarket_fantasy", putting a limit of 20 characters on it. Nobody's reported any problems with the mod's name being that long elsewhere, is this a limitation of the Content DB only or is there something in Minetest that won't be happy with that? I cropped it down to "commoditymarket_fant", but I'm not sure it's a good idea to have the mod name and Content DB technical name not match.

##### Steps to reproduce

Attempt to create a technical name that's longer than 20 characters and Content DB will disallow it.

**Comment by rubenwardy** [comment]
The limit in the database is 100 characters, it looks like the form itself deviates from that. I'll fix this at some point

It's worth seeing if there is a maximum modname length anywhere in Mt

Also, having a different mod name on contentdb and the mod itself will result in the mod being installed incorrectly, so don't do that

**Comment by FaceDeer** [comment]
Could you hold off on approving that mod in the content DB until this issue is fixed, in that case? Or should I withdraw it for now? I'd rather not change the mod's actual name over on minetest-mods since it's already in use by servers in the wild.

**Comment by SmallJoker** [comment]
FYI: There is no mod name length limit in Minetest. As long it only contains the allowed characters it'll be loaded.

**Comment by rubenwardy** [comment]
https://github.com/minetest/contentdb/commit/9de219fd80cf6c441e61850062707d3ef329e0e0
