### ISSUE TITLE
Add continuous integration app: show GitLab statuses

### ISSUE THREAD

**Issue by Panquesito7** [minetest/contentdb#193]
## Problem

There's no continuous integration app in this repository.
I think it would be nice to add some CI app such as Travis CI or GitHub actions.

## Solutions

Create a workflow file checking all the code in this repository.

## Alternatives

Post them right here. 🙂

**Comment by rubenwardy** [comment]
CI is here: https://gitlab.com/minetest/contentdb/pipelines
