### ISSUE TITLE
Score is flawed, if not broken

### ISSUE THREAD

**Issue by appgurueu** [minetest/contentdb#195]
## Summary
The content scores are flawed. Take [Cellestial Game](https://content.minetest.net/api/packages/LMD/cellestial_game/) and [Juanchi Game](https://content.minetest.net/api/packages/runs/juanchi/) as examples.

|-|Cellestial|Juanchi|
|-|-|-|
|Score|119.2|435|
|Downloads|226|161|
|Added|2020-03-26|2019-05-25|

Juanchi has gained less downloads over a longer timespan, but has a significantly better rating.

While this possibly is related to ["fix scores not degrading due to missing session.commit()"](https://github.com/minetest/contentdb/commit/b0f32affcb9b1c053ccfd6e484a1e11faaf5497d), I think that scores in general should be far more transparent, being `total downloads / time available`

After checking the code, I also found some other flaws:

* Unfree content gets only 10% of the score of free content
* Forum posts grant bonuses comparable to downloads

**Comment by rubenwardy** [comment]
Not a bug. Juanchi has score from the forum post, because it was created before the scoring system was created. Cellestial receives score only from its downloads. Juanchi's downloads should be decreasing per day

**Comment by rubenwardy** [comment]
> Unfree content gets only 10% of the score of free content

This is intentional

> Forum posts grant bonuses comparable to downloads

Only when explicitly ran by the admin, which it hasn't been in a year
