### ISSUE TITLE
Download numbers drop as old releases are removed. 

### ISSUE THREAD

**Issue by FreeLikeGNU** [minetest/contentdb#200]
## Summary
Download numbers drop as old releases are removed. This seems like odd behavior, is it intentional? 

##### Steps to reproduce
Post a release
Download(s) the release
Remove the release

**Comment by rubenwardy** [comment]
Downloads are counted per release, not per package.
This is causing havoc with my monitoring graphs, which don't expect the downloads to decrease

**Comment by FreeLikeGNU** [comment]
This would be much appreciated!

**Comment by FreeLikeGNU** [comment]
Many thanks!
