### ISSUE TITLE
Wrong forum topic linked to my mod

### ISSUE THREAD

**Issue by appgurueu** [minetest/contentdb#201]
## Summary
See [`item_limit`](https://content.minetest.net/packages/LMD/item_limit/), it links [this thread](https://forum.minetest.net/viewtopic.php?t=22368) under "Similar Forum Topics" which is unrelated.

My unadded topics list also contains it.

**Comment by rubenwardy** [comment]
that's due to the data loss on the forums last year

**Comment by appgurueu** [comment]
Could you manually edit the DB to remove such entries?

**Comment by rubenwardy** [comment]
I guess I could list all the forum topics where the author doesn't match the ContentDB author, to find definite mismatches

Then there could be some checking based on titles and modnames

**Comment by AntumDeluge** [comment]
Has this been fixed? I don't see the thread listed under "Similar Forum Topics".

**Comment by appgurueu** [comment]
> Has this been fixed? I don't see the thread listed under "Similar Forum Topics".

I still see it.

**Comment by AntumDeluge** [comment]
This is what the page looks like to me:
![item_limit-ContentDB_page](https://user-images.githubusercontent.com/3631473/122463230-33f35480-cf6a-11eb-8559-f961f1d81037.png)

**Comment by appgurueu** [comment]
> **Edit:** Are "Similar Forum Topics" only shown to the author?

Yes.

![Image](https://user-images.githubusercontent.com/34514239/122463448-e7ce0180-cfb5-11eb-953e-592ae89a8409.png)

Interestingly, the title is correct; the link however still points to the wrong forum topic.
