### ISSUE TITLE
NON-FREE issues

### ISSUE THREAD

**Issue by runsy** [minetest/contentdb#202]
I have two complaints:

1) To penalize mods that have not 100% Open Source licenses by dividing them by 10 seems to me exaggerated. This should be reviewed.

2) Putting those mods as NON-FREE in red letters, seems to me exaggerated too, because it is marked with a "scarlet letter" as in medieval times which means it is something bad, or contains pirated content, which is not normal, why in red?

**Comment by appgurueu** [comment]
Non-free content needs to be penalized. Dividing them by 10 is indeed questionable. The warning is appropriate, and red is the perfect color to use for warnings (one could contemplate going with a shade of yellow/orange though, as those are often used for less severe warnings).

**Comment by runsy** [comment]
I think it should be decided by a committee of wise men by vote.

**Comment by Calinou** [comment]
@runsy Voting is generally considered a last resort when taking decisions. Working by *consensus* is often a better idea.

**Comment by rubenwardy** [comment]
The factor of 10 was chosen when there was no filter to hide nonfree packages in the minetest client. Now that's the case, it's worth reconsidering the penalty

**Comment by Aurailus** [comment]
I think it's a fair penalization.

**Comment by benrob0329** [comment]
Minetest thrives off of community cooperation and sharing, non-free licensing stands directly against that.

**Comment by appgurueu** [comment]
> red letters

The letters are actually white and the background is red, so the comparison with a scarlet letter is questionable (although it is of course warning users and indicating danger).

**Comment by runsy** [comment]
> Minetest thrives off of community cooperation and sharing, non-free licensing stands directly against that.



> Minetest thrives off of community cooperation and sharing, non-free licensing stands directly against that.

the matter is how much

**Comment by benrob0329** [comment]
~~I don't know, 10 reads the same as a 2 in my hard drive~~

While I agree that given non-free mods 1/10th the listing power is silly, my personal solution would be to just not allow proprietary licenses at all since they tend to breed toxic behaviors amongst community members but a loud enough minority want them that we need to allow them.

So if we're going to allow them, it shouldn't be a waste of time to put them on CDB, so while a penalty is warranted I don't think it needs to be quite as much.

**Comment by rubenwardy** [comment]
also #151

**Comment by berengma** [comment]
I am against penelties. Do place warnings if mods contain nonfree media or even code.
Registered users should be able to opt-in a filter for nonfree stuff. Opt-out is equal to censorship.

**Comment by rubenwardy** [comment]
https://github.com/minetest/contentdb/commit/ed78a2e06f7bb3090cf11632eccbfac3aa335030
