### ISSUE TITLE
Split code into modular packages inside a monorepo

### ISSUE THREAD

**Issue by mercorii** [minetest/contentdb#203]
## Problem

Contentdb is one big package.

Problems:

1. Server side code is entangled with the client side code. 
2. Database code seems to be entangled with the site code. 
3. There's javascript inside a python package.

## Solution

Convert the repository into a monorepo, and split the project into multiple separate packages inside the monorepo.

Benefits:

1. different packages could be developed separately from each other. 
2. packages wouldn't need to know about internal decisions made in other packages, (as interaction would happen through the public interfaces of the packages)
3. messy code would be harder to write, or at least easier to spot (as there would be clearer rules for interoperability between packages)
4. package development would require less knowledge about every other part of the repository, and would thus become easier, (as the borders of a package would be clearer, and required dependency packages would be easier to check) 

### Ways to split:

* language (python vs js)
* database vs site
* server vs client

#### python vs js

The languages should be separated at the top level into their own top level folders (folder names could be "javascript" and "python"). This way, the division between languages would be clearer. Inside the language folders, code should be split into separate packages, that would only be used via package manager (this is possible in js, not sure about python). The benefit from this would be that javascript devs could easily only look at the javascript code, and python developers wouldn't need to consider javascript.

JS package manager [yarn](https://yarnpkg.com/) allows the use of workspaces as a way to divide single repository into multiple packages. The way it works allows also other languages to nicely live in the same repository. You declare a folder (in yarn's config) to hold all js packages in that repository, give it a name (default is 'packages', but in a multi-language repository "javascript" would probably be better), and then all folders inside the workspaces folder act as their own separate workspace, that can use other packages in that repository via the package manager. This way each package doesn't need to know whether other packages come from npm (or some other package source) or from the same repository. This makes the code more modular, as there's no relational links between files in different packages.

There are probably similar tools for python.

#### database vs site

It seems that the database could be separated from the content.minetest.net site. (My python is bit bad, so I'm not totally sure what happens on that side). They are now both in the same entangled code. 

Instead, database could provide an api (rest, graphql, etc), that the site would then interact with, just like any other api user.

Benefits from this would include:
* more modular design (easier to argue about relations between different parts of code)
* contentdb site would be a regular api user, just like engine is now (to my understanding)
* development of site and db would be independent
* rewriting site in another language would be possible if wanted

#### server vs client

On the concept of the site, perhaps a more modern approach would be to create a separate client package for handling javascript code.

Added benefit would be the possibility to use tools like [storybook](https://storybook.js.org/) for developing smaller individual parts of the frontend (components etc), without need to run the application's own backend. This way, developers without python experience could develop javascript parts.

### Example folder structure:

```
python\ # python packages
  db\
  site\ # if site is kept in python 
  api\
  ...
  additional-future-python-pkg
javascript\ # javascript packages
  site  # if site is rewritten in js
  client\
  client-components\
  ....
  additional-future-js-pkg\
```

It would be possible to start moving towards the proposed folder structure incrementally.

For example, a javascript rewrite of the client side code as a separate package could be developed incrementally using the proposed system:

1. code could be placed as a separate package under "javascript" folder, following the proposed structure. 
2. It could be published to npm or github package management, 
3. from where it could then be consumed as packages in the current implementation using a package manager.

**Comment by Calinou** [comment]
I'd say ContentDB is small enough to not warrant making things more complex with a monorepo, but that's just me.

Keep in mind most contributors to ContentDB are not full-time web developers, and therefore may not have time to learn lots of tooling.

**Comment by mercorii** [comment]
> I'd say ContentDB is small enough to not warrant making things more complex with a monorepo, but that's just me.

> Keep in mind most contributors to ContentDB are not full-time web developers, and therefore may not have time to learn lots of tooling.

Both good points.

**Comment by rubenwardy** [comment]
ContentDB is designed such that it works without the JavaScript. There's not much JavaScript, it's a static resource to provide a better UX. The client-side code is also only in `app/public/static`

The database already runs as a separate instance to ContentDB - it's a PostgreSQL server. The database code in the python package is essentially the client to the instance, with some stuff on migrations and schema.

It's worth noting that ContentDB already has functionality split into modules using blueprints

**Comment by rubenwardy** [comment]
Some easy wins here:

- The Minetest Checker package could be moved from app/tasks/minetestchecker to just minetestchecker. It's a custom library that doesn't depend on anything. It provides the function of checking whether a folder is a valid mod/texture pack/etc
- Maybe move more stuff into blueprints, and perhaps make blueprints packages? Idk

**Comment by rubenwardy** [comment]
> Keep in mind most contributors to ContentDB are not full-time web developers, and therefore may not have time to learn lots of tooling

ContentDB hasn't had many contributes - one or two people fixing typos. Using Docker is already a high barrier to entry, I guess
