### ISSUE TITLE
Broken links: scores REST API and Prometheus metrics

### ISSUE THREAD

**Issue by Zughy** [minetest/contentdb#206]
## Summary
Broken links at the end of this document: https://github.com/minetest/contentdb/blob/master/app/flatpages/help/top_packages.md

I... guess it simply misses the implementation of those APIs?

##### Steps to reproduce
Click on those links

**Comment by rubenwardy** [comment]
you need to view the actual web version here: https://content.minetest.net/help/top_packages/
