### ISSUE TITLE
Add tags for content curation

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/contentdb#210]
I suggest to add a couple of tags to improve content curation:

* Finished: The thing is officially finished, according to the author. “Finished” means the thing has reached completion, the author's goals have been reached and that it's in a release-worthy shape, suitable for publication. It's usually version 1.0 or similar. “Finished” does NOT mean “the final version ever” or “perfection”, it's perfectly fine to have updates long after the 1.0 release.
* Playable: Reserved for games. This is for games that have enough decent gameplay and stability to be worthwhile for most players, even if they are not officially Finished yet. Very early tech demos will be excluded by this. This tag is usually equivalent with beta versions of games
* Very buggy: The thing has some high-profile bugs. High-profile means: Frequent crashes, freezes, security vuln, very low performance, game-breaking bugs, etc. Note: Bugs only apply if they happen in any of the designated Minetest versions
* Broken: The thing is so broken, it's unusable (this might imply hiding the thing as well)
* Complex installation: The thing does not work out of the box when installed, extra steps are required (example: Inside The Box)
* Featured: A featured game (#9530). How exactly this is decided still needs to be discussed. But the idea is that this tag is later used by Minetest and the website for special treatment

Minetest could automatically filter out all games that are neither Finished nor Playble (whitelist/blacklist).
Also, everything that has one of these bad tags is also automatically filtered out in Minetest: Broken, Very buggy, Complex installation.

This new tagging system should help a little bit in filtering out most content that is unsuitable to a larger audience.

**Comment by rubenwardy** [comment]
Featured tag has been added

**Comment by rubenwardy** [comment]
I've added Complex Installation.

I'm not sure about the rest of the tags - I feel like #160 would be a better way to deal with that

**Comment by rubenwardy** [comment]
Closing in favour of #160 (which will be resolved soon)
