### ISSUE TITLE
Atom/RSS/JSON feed

### ISSUE THREAD

**Issue by louisroyer** [minetest/contentdb#224]
## Problem

I would like to suscribe to a feed containing recently added mods.

## Solutions

It would be nice if you could implement some [Atom feed](https://en.wikipedia.org/wiki/Atom_(Web_standard)) for recently added mods.

**Comment by rubenwardy** [comment]
@Warr1024

**Comment by rubenwardy** [comment]
Steps:

- Create new blueprint at `app/blueprints/feed/__init__.py`
- Add a route called feed which returns Atom or RSS information. Build the query and the XML here, I'd prefer it if models.py wasn't modified
- Profit

**Comment by Lazerbeak12345** [comment]
Would it be possible to have seperate feeds for each mod's releases? I'm thinking something like `https://content.minetest.net/packages/$USER/$PACKAGE/feed.xml` (linked of course).

Ofc I can just split this to be a seperate issue, if you'd prefer.

**Comment by GreenLunar** [comment]
This is an important feature. What's the priority of this?

**Comment by Lazerbeak12345** [comment]
It seems like rubenwardy approved it. A PR seems to be what we're waiting for.

I've got some professional experience with Django. I could throw this on my personal developer backlog - but it's not very high priority for me to implement personally so it would take some time.

**Comment by Lazerbeak12345** [comment]
Do we want RSS, Atom or both?

**Comment by GreenLunar** [comment]
I prefer Atom and JSON.
I'd like to help with this task.
Please tell me what you want me to do.

**Comment by Lazerbeak12345** [comment]
My workload got _much_ larger at the beginning of the year. I'm not currently working on this.

**Comment by rubenwardy** [comment]
https://content.minetest.net/help/feeds/
