### ISSUE TITLE
Change the main thumbnail

### ISSUE THREAD

**Issue by runsy** [minetest/contentdb#225]
## Problem

I want to change the main screenshot/thumbnail for my game. But I can not, because:

- I cannot replace it.
- The thumbnail is always the first one. I would have to delete all them and upload again.

## Solutions

- A checkbox to set a particular uploaded image as the thumbnail, as in Nexus Mods.

## Alternatives

- A replacement option.

**Comment by rubenwardy** [comment]
Duplicate of #125
