### ISSUE TITLE
Add ability for packages to specify compatible games

### ISSUE THREAD

**Issue by IFRFSX** [minetest/contentdb#232]
On the minetest content, every mod and texture_pack release adds an optional information <game> to remind the player which game_package these mod/texture are applicable to.

**Comment by rubenwardy** [comment]
Are you asking for packages to state the games they are compatible with?

**Comment by IFRFSX** [comment]
@rubenwardy 
yes, you can understand it this way. ; )

**Comment by rubenwardy** [comment]
I think the best way to do this would be a many-to-many relation on package-to-package. Authors would then specify compatible games manually in the edit form.

I'll have some logic to detect compatible games for example - if you depend on default, you probably only support MTG. This will run on all mods when the system is first released, to populate the relations.

Questions:

1. I'm wondering how to deal with conflicts between user-specified and detected dependencies - ie: the user should be able to remove an incorrect guess of game dependency. One way around this is to only run the detection once or manually, and then show warnings if the user hasn't specified anything.
2. Should mods that support all games (typically library mods) have no games in the relationship, or all games?  
  If all games, how would further relations be added when games are uploaded?  
  If no games, how should we detect mods where the user hasn't yet filled out the supported games?

**Comment by Warr1024** [comment]
It seems to me that the most reasonable thing to do is to allow authors to assert a compatibility relationship, assert an incompatibility relationship, or make no assertion.  If no assertion is made then the system's inferences can be used.

We could also allow the community (other users) to vote on their own assertions, and add that as a layer between the author's and system's assertions. CDB just shows whichever assertion has the highest precedence, descending from author to community to system, and the system will always make at least some guess.

It would also be good to show the origin of a compatibility assertion (by author, by system, etc.) so there's no misattribution.  Lower-priority assertions can be "dimmed" in some way.

If a package is very widely compatible we can trim down the list to only the top N, sorted by precedence of the assertion descending (i.e. keep the author's and trim system ones by default), and then sorted by score descending for tiebreaking (top packages that users are more likely to be interested in).  Could trim the list, or fold it up, beyond N.

As an alternative, if a package is compatible with almost every game in the system (more than a certain %, or fewer than some N incompatibilities) then we could show a "universal" label, and only show the _incompatible_ exceptions.

**Comment by IFRFSX** [comment]
> 
> 
> 我认为最好的方法是在包到包上建立多对多关系。 然后，作者将在编辑表单中手动指定兼容的游戏。
> 
> 例如，我会有一些逻辑来检测兼容的游戏——如果你依赖默认值，你可能只支持 MTG。 这将在系统首次发布时在所有模组上运行，以填充关系。
> 
> 问题：
> 
>     1. 我想知道如何处理用户指定的依赖项和检测到的依赖项之间的冲突 - 即：用户应该能够消除对游戏依赖项的错误猜测。  解决此问题的一种方法是仅运行一次或手动检测，然后在用户未指定任何内容时显示警告。
> 
>     2. 支持所有游戏的模组（通常是库模组）是否应该在关系中没有游戏，还是所有游戏？ 
>        如果是所有游戏，上传游戏时如何添加进一步的关系？ 
>        如果没有游戏，我们应该如何检测用户尚未填写支持游戏的模组？

For the first question, I suggest you add a manual detection function.
The second question can be displayed as "support all games", and then write clearly "if you use it in a game, what functions will it perform" in the README file or the work introduction.

**Comment by rubenwardy** [comment]
You can now use `supported_games` and `unsupported_games`
