### ISSUE TITLE
c++ curl request error

### ISSUE THREAD

**Issue by brtkuu** [minetest/contentdb#233]
When I'm trying to send request about package by author name and package name using curl lib in c++, I'm getting page with redirect to other page and i can't handle response because it's throwing me an error.
![image](https://user-images.githubusercontent.com/55049549/92457746-e66cde80-f1c4-11ea-8cad-0e90aaae725b.png)

**Comment by SmallJoker** [comment]
```
curl -i https://content.minetest.net/api/packages/gundul/water_life/releases
HTTP/2 308 
server: nginx
date: Tue, 08 Sep 2020 13:25:18 GMT
content-type: text/html; charset=utf-8
content-length: 343
location: http://content.minetest.net/api/packages/gundul/water_life/releases/
```

Use `curl -L <url>` to follow redirects, or append a tailing slash. Both will work. The error in your screenshot is caused by a failed attempt on parsing HTML as JSON.

**Comment by rubenwardy** [comment]
Probably bad that it redirects to the non-https version, I probably need to set up proxy redirects intercepts
