### ISSUE TITLE
`413 Request Entity Too Large` on release upload

### ISSUE THREAD

**Issue by nonchip** [minetest/contentdb#235]
uploading a release zip (50MB) for a game (which is why it's so large, and no i can't use vcs import due to a build process being required) i get a HTTP 413.

especially for games, 50MB should be a reasonable size, please increase the allowed upload file size in your nginx config.

alternatively, since you already download from vcs anyway, how about allowing people to paste a HTTP(S) URL that then gets downloaded by the server?

For the record (and/or testing/seeing what i was doing/etc), i was trying to upload [this file](https://gitlab.com/worstconcept/worstblockgame/-/jobs/745052811/artifacts/download) generated via CI from [this repo](https://gitlab.com/worstconcept/worstblockgame) (Release tag "[0.2.0](https://gitlab.com/worstconcept/worstblockgame/-/releases/0.2.0)"), to [this not-yet-approved-because-i-cant-add-a-release game page in the contentdb](https://content.minetest.net/packages/nonchip/worstblockgame/)

**Comment by rubenwardy** [comment]
The maximum upload is currently 32MB, I'll have to re-evaluate what a sensible limit is

**Comment by rubenwardy** [comment]
I've increased the limit to 100MB

**Comment by nonchip** [comment]
now the upload succeeded, then i got "Working..." and then:

> Task Failed
`Unknown server error`

**Comment by rubenwardy** [comment]
Apparently there's a deadlock, maybe try again?

**Comment by nonchip** [comment]
done, worked this time, thanks.
