### ISSUE TITLE
run_migrations.sh does not run with empty ("") SECRET_KEY

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest/contentdb#244]
## Summary
Executing `./utils/run_migrations.sh` does not work if the `SECRET_KEY` in `config.cfg` is empty (default)

##### Steps to reproduce
Follow the setup steps in the readme

Step 7: "Setup database" fails with:
```
  File "/usr/local/lib/python3.6/site-packages/flask_user/user_manager.py", line 197, in init_app
    self.token_manager = TokenManager(app)
  File "/usr/local/lib/python3.6/site-packages/flask_user/token_manager.py", line 43, in __init__
    raise ConfigError('Config setting SECRET_KEY is missing.')
flask_user.ConfigError: Config setting SECRET_KEY is missing.
```
## Workaround

Set a non-empty `SECRET_KEY` in `config.cfg` for example:

```
SECRET_KEY = "1234"
```

**Comment by rubenwardy** [comment]
Don't the steps tell you to set this key? It's needed to run the app image with the flask server. Technically, the migration could run in different container I guess
