### ISSUE TITLE
Quoted text is displayed as normal

### ISSUE THREAD

**Issue by Zughy** [minetest/contentdb#255]
## Summary
As the title says

##### Steps to reproduce
Practical example => https://content.minetest.net/threads/375/
![imagen](https://user-images.githubusercontent.com/63455151/102528101-5d582400-409e-11eb-8b7f-daad2729c037.png)

P.S./OT: I hoped it was on GitLab :(

**Comment by rubenwardy** [comment]
Thanks for the report, this will be due to the whitelisting of HTML tags I use - I can add blockquote to the whitelist


> P.S./OT: I hoped it was on GitLab :(

Unfortunately not

**Comment by rubenwardy** [comment]
Fixed, it's actually a CSS issue

https://github.com/minetest/contentdb/commit/d7d9131de810b5a213c10b4d0b6fad0671ef2f47
