### ISSUE TITLE
Downloaded Zip should have content name

### ISSUE THREAD

**Issue by appgurueu** [minetest/contentdb#257]
It would be useful if downloaded releases were named `<contentname>-<releasename>.zip` or the like instead of `<hash>.zip`. This can be achieved using the HTML5 `download` attribute.

**Comment by Warr1024** [comment]
FYI this can _also_ be done with the HTTP Content-Disposition header, which may help catch cases where someone shares a link directly to a zip.

**Comment by rubenwardy** [comment]
zips are served directly from nginx (actually this may be broken), which doesn't have access to the DB to find out the necessary info. This would need to be implemented using the download attribute, or by actually naming files correctly

Related #116
