### ISSUE TITLE
Copy and paste from clipboard via Mouse3 (middle mouse button) doesn't work in the javascript editor on the website.

### ISSUE THREAD

**Issue by voxel-minetest** [minetest/contentdb#292]
In the search mask it works, also in the editor field, when javascript is disabled. 
With javascript enabled, only Ctrl+C and Crtl+V will do the job in the editor.

**Comment by rubenwardy** [comment]
Upstream issue. Please report at https://github.com/Ionaru/easy-markdown-editor

**Comment by voxel-minetest** [comment]
Oh.. ok.

**Comment by rubenwardy** [comment]
I suggest copying the description there

**Comment by voxel-minetest** [comment]
Was redirected again, I'm so sick of shitty software... -.-

Anoying javascript trash... 
I will just disable it for contentdb. 
I think I only allowed it because linking wasnt working as expected. 
Nevermind I will do this with html tags... 

Please never make it that site depends on js!

**Comment by rubenwardy** [comment]
You could just ctrl+v

**Comment by voxel-minetest** [comment]
> You could just ctrl+v

I know of course and I did that, but it is annoying. 
`Mark -> click `
that's the way to go, not
`Mark -> ctrl+c -> click -> ctrl+v`
...
But we are still living in a Micr$oft world, at least on desktops. 
=(
