### ISSUE TITLE
New Tag: commerce

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/contentdb#299]
Requesting tag `commerce` and/or `trade` for mods that are primarily intended for trade/commerce environments in games.

Examples:
- [currency](https://content.minetest.net/packages/VanessaE/currency/)
- [atm](https://content.minetest.net/packages/CodeMiner/atm/)
- [server_shop](https://forum.minetest.net/viewtopic.php?t=26645)

*I didn't see anywhere on ContentDB to request new tags. If this isn't the best place for it, please let me know where is.*

**Comment by rubenwardy** [comment]
Yes, this is the correct place

Thanks for the suggestion! Added it now
