### ISSUE TITLE
Tags for Mods Primarily Focused on Chat/Console

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/contentdb#300]
Requesting tag(s) for mods that primarily focus on player chat/communication or who's primary function is interacting with the console.

Suggestions:
- `chat`
- `chatlog`
- `communication`
- `playerchat`
- `console`

Mod examples:
- [chatlog](https://forum.minetest.net/viewtopic.php?t=18287)
- [listitems](https://content.minetest.net/packages/AntumDeluge/listitems/)
- [emoji](https://content.minetest.net/packages/bosapara/emoji/)
- [announce](https://forum.minetest.net/viewtopic.php?t=16823)
- [irc](https://content.minetest.net/packages/kaeza/irc/)

**Comment by rubenwardy** [comment]
Done
