### ISSUE TITLE
markdown support seems full in review editor, but isnt

### ISSUE THREAD

**Issue by AFCMS** [minetest/contentdb#304]
## Summary
![image](https://user-images.githubusercontent.com/61794590/120813749-7bcbb200-c54e-11eb-86cb-7d07e5d33630.png)
![image](https://user-images.githubusercontent.com/61794590/120813813-8c7c2800-c54e-11eb-8985-06033008466c.png)

##### Steps to reproduce
try

**Comment by rubenwardy** [comment]
Strike throughs aren't supported by the Markdown "spec", they're a common extension but not part of Markdown itself

The correct fix to this is to enable the extension in the markdown parsrt

**Comment by AFCMS** [comment]
but it seems it works in editor, so why not in real review? :thinking:

**Comment by rubenwardy** [comment]
The editor is a separate piece of software to ContentDB. It's a JavaScript library, I didn't write it. It appears to have more extensions enabled by default

**Comment by AntumDeluge** [comment]
Does ContentDB's markdown implementation support `<del>` tag?

**Comment by AntumDeluge** [comment]
There are however, issues with tables. They work in the description & the previewer, but don't display correctly in comments:

![ContentDB_comment_tables](https://user-images.githubusercontent.com/3631473/124346247-a97a3a00-db92-11eb-9d55-d7f1d1af66ca.png)

**Comment by AntumDeluge** [comment]
Also, I just learned that GitHub & Discord markdown implementations support enclosing with double tildes (~) for strikethrough:

&#126;&#126;deleted&#126;&#126; = ~~deleted~~
