### ISSUE TITLE
Option to Request/List Alternatives

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/contentdb#306]
I would like to be able to have an option to request that an admin review and add a mod as an alternative to be listed on my mod's page. An example would be that I want to request that [chat_record](https://content.minetest.net/packages/Emojiminetest/chat_record/) be listed on my [chatlog](https://content.minetest.net/packages/AntumDeluge/chatlog/) mod page as an alternative. This would just be a way to acknowledge mods that can be used in place of others. It would be similar to the "Similar Forum Topics" section.

Currently, we can use tags to sift through similar mods. But I think this would be a good way for authors to specifically denote alternative mod.

**Edit:** Actually, this can be done by simply listing alternatives in description. So maybe this idea isn't too useful. Still, I'll leave it open for an admin to close if they feel it is pointless. Still might be a good option for ContentDB to list alternatives.

**Edit:** I guess there is already a "Related" section (which I believe uses some kind of autodetection?). Perhaps there could just be a field where authors could request that another mod be listed under this section.

**Comment by rubenwardy** [comment]
I don't have time to implement every suggestion for ContentDB. I think packages should just add to their long desc for now
