### ISSUE TITLE
Allow to share maps to ContentDB

### ISSUE THREAD

**Issue by Emojigit** [minetest/contentdb#311]
## Problem
I want to share my minetest map with others, but I cannot find a proper platform to do so. Even though I post it on the best platform now, Minetest Forum, it is hard to install maps by non-devs.

## Solutions
If we add a "map sharing" option in CDB (and in-game content browser), then all will be fine. I also suggest adding a button to export maps to CDB in Minetest main menu (this requires a login page in Minetest Engine for CDB).

**Comment by rubenwardy** [comment]
Duplicate of #162
