### ISSUE TITLE
RSS or Atom feed

### ISSUE THREAD

**Issue by Emojigit** [minetest/contentdb#313]
## Problem

My new tab software (renewed tab) allows me to subscribe to get RSS or Atom feeds, but I cannot find one for ContentDB.

## Solutions

Add some type of feeds that related to specified events, e.g. new contents, my content update, thread update, etc.

**Comment by Emojigit** [comment]
dup #224, but afaik this provides more info

**Comment by rubenwardy** [comment]
https://content.minetest.net/help/feeds/
