### ISSUE TITLE
Wanted Packages

### ISSUE THREAD

**Issue by AntumDeluge** [minetest/contentdb#316]
Would there be a way to add a "wanted packages" section? It seems that there are many mods where the creator is no longer active or they are just not yet added to ContentDB. If there was a section that showed packages that users would like to see in ContentDB, more active modders might be willing to fork & update the old mods.

**Comment by rubenwardy** [comment]
This would be better as a forum thread

**Comment by AntumDeluge** [comment]
Good point.

**Comment by AntumDeluge** [comment]
Thread created: https://forum.minetest.net/viewtopic.php?f=5&t=28651
