### ISSUE TITLE
Download link does not contain the mod folder

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/contentdb#319]
## Problem

If you click the download link of a mod in the website, you only get the contents of the mod folder, not the mod folder itself. This is annoying when extracting the mod and also violates forum rules for the Mod Releases subforum.

## Example (to reproduce)

https://content.minetest.net/packages/Wuzzy/calendar/

## Solution

Make it so the download link on the ContentDB website includes the Zip with the mod folder. The folder name could be based on mod.conf.

Thanks for reading.

**Comment by rubenwardy** [comment]
This only happens with old uploads. New uploads will have the mod folder

I haven't been especially motivated to migrate the old uploads to this form

**Comment by Wuzzy2** [comment]
OK, so how can I manually update my old packages?

**Comment by rubenwardy** [comment]
You'll need to create a new release
