### ISSUE TITLE
"MIT" license is ambigious -- is "Expat" or "X11" meant here?

### ISSUE THREAD

**Issue by emixa-d** [minetest/contentdb#326]
"MIT" is in the list of accepted licenses for mods on <https://content.minetest.net>.
This is ambiguous however, as "the MIT license" has been used to refer to the Expat license, and sometimes to refer to the X11 license (see <https://www.gnu.org/licenses/license-list.en.html#Expat>).

The difference isn't very important in practice, but I'm writing an ‘importer‘ for Guix for automatically packaging Minetest mods, and packages in Guix need accurate licensing metadata.

I'd recommend removing "MIT" from the licenses that can be chosen from (allowing ‘old’ mods to keep the ambigious ‘MIT’ for now), adding "Expat" and "X11" to the list, and noting that people often mean "Expat" when they say "MIT" on the web interface were the license is chosen (to avoid confusion).

Alternatively, maybe "MIT" can be replaced with "MIT (Expat)"  on the web interface, like this:

old:
```
Type
    Mod
Technical Name
    farming
License
    MIT 
Added
    2018-05-23 19:58 UTC
```

new:
```
Type
    Mod
Technical Name
    farming
License
    MIT (Expat)
Added
    2018-05-23 19:58 UTC
```

**Comment by Calinou** [comment]
It means the Expat license, but I think we should keep the MIT identifier for two reasons:

- It's more commonly used. A lot of people don't know what Expat is.
- It's the SPDX identifier.

**Comment by emixa-d** [comment]
Ok, thanks for the clarification!  I'll let the importer interpret "MIT" as "Expat", with a link to <https://github.com/minetest/contentdb/issues/326#issuecomment-890143784>.

**Comment by rubenwardy** [comment]
ContentDB now contains all FSF/OSI SPDX licenses, and links to the SPDX page for each when used
