### ISSUE TITLE
Screenshot Acceptable Content Policy

### ISSUE THREAD

**Issue by Warr1024** [minetest/contentdb#333]
We should provide a policy/guide on screenshots, in order to better control the quality of images on the site, provide guidance to authors in choosing screenshots, and provide a checklist for editors evaluating screenshots.

- Screenshots must not violate copyright.  This SHOULD be obvious, but some users seem to not know that just because you found an image in Google Image search and it didn't have a copyright notice on it doesn't mean you're allowed to use it as you see fit, and that altering an image and using it as a background in a composite shot still requires licensing.
- Screenshots should not be misleading, e.g. do not use idealized mockups or blender concept renders if they do not accurately reflect in-game appearance.
- Screenshots should depict the actual content of the package in some way, i.e. no "off topic" images.
- Content that is prominently displayed or "focal" should be either present in, or interact with, the package in some way.  These can include things in other packages if they have a dependency relationship (either way), or if the submitted package in some way enhances, extends, or alters that content.  Unrelated package content can be allowed to show what the package content will look like in a typical/realistic game scene, but should be "in the background" only as far as possible.
- Screenshots cannot contain content that falls outside the Content Warnings for a package.  A farming mod that does not itself add illicit drugs (and thus does not have a Drugs warning) cannot show illicit drugs being farmed in the background of the image.
- Images should be MOSTLY screenshot when possible.  Some alterations are okay, such as collages, added text, some reasonable compositing.  Logo/brochure images are allowed but should NOT be the cover image.  Don't just use one of the textures from the package; show it in-situ as it actually looks in the game.
- Packages should have a screenshot when reasonably applicable.  Specifically, we may want to be able to withhold package approval for a package that should reasonably be able to provide a screenshot but does not.
- Screenshots should be of reasonable dimensions.  Authors should be able to capture at 720p or so, and not rely on the 320x240 thumbnail screenshot.png that's embedded in a package.  If an author is unable to create a reasonable screenshot for technical reasons (e.g. people on old enough computers that require them to use subsampling) then CDB editors could help out (but the package author would need to grant permission).
- Screenshot should be of a reasonable byte size, i.e. at least use "high compression" settings for PNG, use optimized coefficients / progressive encoding for JPEG.

**Comment by Calinou** [comment]
To add to this:

- Screenshots should use the default graphics settings and texture pack, unless the screenshot is meant to demonstrate a custom texture pack.
