### ISSUE TITLE
No full URI encoding support

### ISSUE THREAD

**Issue by appgurueu** [minetest/contentdb#335]
Try visiting https://content.minetest.net/packages/Hugues+Ross/rpg16/?protocol_version=40

`https://content.minetest.net/packages/Hugues Ross/rpg16/?protocol_version=40` works however (note the space).

**Comment by appgurueu** [comment]
Turns out `%20` works. Still, `+` should work too?

**Comment by rubenwardy** [comment]
not an issue with ContentDB
