### ISSUE TITLE
Unapproved packages pages are strange

### ISSUE THREAD

**Issue by AFCMS** [minetest/contentdb#338]
## Summary
* They aren't shown in any tab of cdb, but can be accessed with the URL even if not connected.
* A strange message appears then not connected:

![image](https://user-images.githubusercontent.com/61794590/133041372-da5251a8-7271-45ca-b2bb-4cb033b17d3b.png)

Also, I don't know if its a good idea to allow non editor/non connected users to download and see unapproved packages...

**Comment by Emojigit** [comment]
I think that's good to allow them to download, or even make an official way to see them, to allow them to be a part of commenting. But we have to warn them before download.

**Comment by AFCMS** [comment]
:+1:
