### ISSUE TITLE
User renaming

### ISSUE THREAD

**Issue by appgurueu** [minetest/contentdb#339]
## Problem

Some users might want to change their ContentDB username without deleting their account and creating a new one.

## Solutions

Everything related to the old account should redirect to the new account, at least for a while.

## Additional context

See https://content.minetest.net/users/_Xenon/ and https://content.minetest.net/users/xenonca/ - Xenon has "renamed" their account by leaving the old account around a well as creating a new one, adding it as a maintainer of all packages of the former account. This is quite a good workaround actually.

**Comment by rubenwardy** [comment]
This has already been implemented, waiting for Minetest 5.5.0
