### ISSUE TITLE
OAuth support

### ISSUE THREAD

**Issue by Emojigit** [minetest/contentdb#344]
## Problem
When using the API, it requires a token. But it is hard to do and not user-friendly when be used with a 3rd party CDB client.

## Solutions
In a nutshell: add OAuth.

**Comment by rubenwardy** [comment]
ContentDB now supports OAuth2: https://content.minetest.net/help/oauth/

It's currently invite only and only supports reading public data (so good for a 'Log in with CDB' feature). Let me know if you have a compelling usecase and want to be an early tester
