### ISSUE TITLE
Metapackages page should show forums info

### ISSUE THREAD

**Issue by GoodClover** [minetest/contentdb#345]
## Problem

The metapackages page will show "No packages avaliable" if a metapackage is not avaliable on CDB, but *is* on the forums.
e.g. `computer` from https://forum.minetest.net/viewtopic.php?t=9567 dosen't show in <https://content.minetest.net/metapackages/computer/>

## Solutions

Show a "More content from the forums", the same way as search results do.

I'm not sure of CDB internals, but I presume this would have to be based on normal search, rather than analysis to show what forum post mods *actually* provide the meta-package.<sub>(the fact CDB can even do this with mods on CDB is already amazing)</sub>
This must be made obvious!

**Comment by rubenwardy** [comment]
This is already the case. I believe computers isn't shown because it's discarded. Editors and authors can mark topics as discarded to indicate they're old and not worth being on ContentDB. But this may not be that useful for users

**Comment by rubenwardy** [comment]
OK, so the actual problem here is that the forum topic doesn't have `[computer]`, so ContentDB can't find it
