### ISSUE TITLE
Use URL-based internationalisation selection

### ISSUE THREAD

**Issue by rubenwardy** [minetest/contentdb#349]
Instead of storing languages in cookies, ContentDB should probably use URL prefixes instead.

For example:

```
https://content.minetest.net/fr/
https://content.minetest.net/fr/packages/rubenwardy/conquer/
https://content.minetest.net/fr/user/login/
```

See https://flask.palletsprojects.com/en/2.0.x/patterns/urlprocessors/

**Comment by Calinou** [comment]
I'm not a fan of URL-based internationalization, as it breaks when you share URLs to other people. I don't want to see a page in a language I don't understand simply because I clicked on someone else's link.

**Comment by rubenwardy** [comment]
Yeah I was wondering how to combat this. I currently use cookies

The problem with cookies is that Google won't be able to find the translated versions
