### ISSUE TITLE
Use different teminilogy for the 2 types of review

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/contentdb#354]
## Problem

I'm not sure if I understood it right, but it seems ContentDB has two types of review that are completely different, yet both are called "review".

The first type of "review" is a review that is needed to approve the package (I guess?).
The second type of "review" is the user review, it's when they rate the package.
 
## Solutions

Since both these types of "reviews" are very different, I suggest to use a different term for one of them, to avoid confusion (especially for translators, lol).

**Comment by rubenwardy** [comment]
Before reviews where added, the approval process was called the review process. When I added reviews, I renamed it to the approval process but forgot a few instances such as "review threads"
