### ISSUE TITLE
This URL doesn't work: https://fosstodon.org/web/@Wuzzy

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/contentdb#364]
## Summary
If you add this URL into a game description:

```
https://fosstodon.org/web/@Wuzzy
```

It won't get properly clickable. It turns into two different links, both lead to the wrong webpage.

##### Steps to reproduce
Go to <https://content.minetest.net/packages/Wuzzy/lazarr/> and hover `https://fosstodon.org/web/@Wuzzy`.

**Comment by rubenwardy** [comment]
As a work around, you should explicitly make this a link rather than relying on the markdown processor turning plain text into a link. That's done by wrapping the URL with `<>`:

```md
<https://fosstodon.org/web/@Wuzzy>
```

**Comment by rubenwardy** [comment]
superseded by #537 and #420
