### ISSUE TITLE
Organisation Accounts

### ISSUE THREAD

**Issue by AFCMS** [minetest/contentdb#366]
## Problem

Then you work in team, you can create an dedicated account on cdb to post your packages, but there are many limits to this.

- You have to share the password between the members
- You need to disconnect from your main account and reconnect using the organization account to create mods, customize tokens, profile, etc
- Probably many other things

Then you have created a packages, you can in fact add other people as maintainers, but thats still more difficult than it should be. 

## Solutions

Add special accounts similar to github organizations, allowing to add multiple "owners", "developpers", etc

## Alternatives

?

## Additional context

?

**Comment by rubenwardy** [comment]
There are a lot of requests for ContentDB features and I'm the only one working on it. I don't have time to implement everything

Therefore, I don't think I can implement this feature. I suggest using Firefox containers or a private/incognito window to log into another account
