### ISSUE TITLE
Suggestion: add section for mts file format.

### ISSUE THREAD

**Issue by ksandronline** [minetest/contentdb#367]
Hello. I have a suggestion, sorry if I wrote it in the wrong place.

Add a section to the database for storing mts format files. I think many players will have a nice house, a boat, an airplane, a castle, a stadium and so on that they would like to share with others. Also, when creating maps, it would be convenient to take ready-made objects from the database.

**Comment by rubenwardy** [comment]
Related: #162

**Comment by rubenwardy** [comment]
ContentDB is designed for things that end users can use directly in the client. Supporting MTS doesn't really make sense to this goal

If it's to be used by a mod, then it should be uploaded as a mod. If it's for manual placement by a user, then more consideration is needed
