### ISSUE TITLE
People shouldn't lose their achievements when someone else surpasses them

### ISSUE THREAD

**Issue by Zughy** [minetest/contentdb#371]
## Problem
Let's say John Doe has a game that is currently top n°1. They have an achievement saying "John Doe has a game placed at n°1", but then another user reaches that spot and John Doe automatically loses their title, becoming now n°2.  
This forces people to hustle to always update their contents if they want to keep the achievement, but I think it's healthier (and righter) to not take away from them what they achieved somewhere down the road.  
As someone who's currently top n°1 both with reviews and texture packs, this pressures me.

## Solutions

Change the current achievement system so that when you reach a certain goal, CDB won't take it away from you. Once unlocked, it remains unlocked.  
Achievements could be reworded, such as "John Doe has a game placed at n°1" => "John Doe has a game that reached X spot". So for instance (also) Hugues Ross would have the most helpful reviews even if right now I am the one with that

## Additional context

I don't have a clear formed idea about whether to also keep the current ones or not for now, up to rubenwardy I guess

**Comment by rubenwardy** [comment]
ContentDB currently doesn't store the medals, they're calculated using database queries when loading the profile page.

So either that would need to be implemented, or the medals would need to be replaced with alternatives that are absolute rather than relative

**Comment by Zughy** [comment]
Yey, pressure!

:\
