### ISSUE TITLE
Add “developer tools” tag

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/contentdb#375]
Please add a tag for mods that are devloper tools because mods like `schemedit`, `ltool` and `perlin_explorer` don’t fit into any of the provided categories so far.

I define a “developer tool” as anything that is primarily designed to help mod and game developers develop their things.

**Comment by rubenwardy** [comment]
cone

**Comment by Wuzzy2** [comment]
Nice. I've added the tag to 13 things.

https://content.minetest.net/packages/?page=1&tag=developer_tools
