### ISSUE TITLE
Outdated game jam advertisement

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/contentdb#405]
The ContentDB still shows the 2022 Minetest Game Jam advertisement on front page, but it is over now.

Also, don't forget this:

> Winning submissions (including community winner) will all recieve ContentDB front page promotion.

https://github.com/GreenXenith/minetestgamejam/blob/master/2022/PLANNING.md

(admittedly, I am a little bit biased. :D)

**Comment by rubenwardy** [comment]
a7b6778
