### ISSUE TITLE
Focus Search input on page load

### ISSUE THREAD

**Issue by depascalis** [minetest/contentdb#406]
## Problem

I use CDB mainly to searching for something. After entering the site, It's incredibly painful and inconvenient to move my finger all the way from the keyboard to the touchpad and then perform the gestures needed to put focus on the search input field.
I'd like to input my query as soon as the main page has loaded.

## Solutions
Please put focus on the Search input field on page load.

**Comment by rubenwardy** [comment]
This will be very annoying on mobile, if it shows the keyboard. One alternative would be to add a keyboard shortcut for the searchbar, like ?.

You can currently press tab 7 times to focus the search bar.

Another option is to add ContentDB as a search engine. This would allow searching CDB straight from your browser's searchbar

![image](https://user-images.githubusercontent.com/2122943/205693548-71926206-45d1-4e56-af94-30a69d7ee860.png)
