### ISSUE TITLE
Incorrect markdown rendering of code block in list item

### ISSUE THREAD

**Issue by fgaz** [minetest/contentdb#409]
## Summary

In a mod's readme, this code

    * item
      ```
      line 1
      line 2
      ```

results in inline code like this:

* item `line 1 line 2`

instead of

* item
  ```
  line 1
  line 2
  ```

##### Steps to reproduce

Encountered [here](https://content.minetest.net/packages/fgaz/extruder/) (Settings section). Correct rendering [here](https://sr.ht/~fgaz/minetest-extruder/)

edit: I changed the markdown in contentdb to have a better rendering, but the upstream markdown still triggers the bug

**Comment by rubenwardy** [comment]
This is expected, you need to leave a blank line between the text and the fences

**Comment by rubenwardy** [comment]
There is supposed to be a blank line between the text and the code block, but ContentDB also doesn't support that

**Comment by fgaz** [comment]
I suppose this was closed because it's an upstream issue. Do you know if there is a ticket about it in the upstream tracker?

**Comment by rubenwardy** [comment]
This is intended behaviour by the python markdown parser as markdown _requires_ blank lines between blocks

I'm planning on moving away from python markdown to something a bit less strict, see #537
