### ISSUE TITLE
now moderators can delete good comments as corruption

### ISSUE THREAD

**Issue by mckaygerhard** [minetest/contentdb#413]
This is interesting for those who know rubenwardy... I just saw a despotic fact in the contendb... let's see how many here are so brave to tell him...

I have created (as tenplush does, with many of its plugins that are only improvements of others, not new creations) a good spawn point mod, randomized, a user commented that it was very good and that comment was deleted..

This aroused my curiosity because long before they alleged that it was plagiarism, that is not the case cos i already talked with base code author and all the issues were addresed.. 

but I did not know that @rubenwardy  they had deleted the comment.. as seen in the photo.. I published this so that it can be seen how minetest became a corrupt bureaucracy.. they only promote what they are told convenient ???? or what?

![image](https://user-images.githubusercontent.com/1571724/210246579-4cd13377-aa4d-4544-b6d9-4fd051cc13a1.png)

https://web.archive.org/web/20230102144930/https://github.com/minetest/contentdb/issues/413

**Comment by rubenwardy** [comment]
I converted it into a thread, the package had never been submitted for approval so they should have never been able to make a review

**Comment by mckaygerhard** [comment]
i cannot understand so much..  the package neeed aproval? looks llike google play.. puff.. why just users dont just use they want to use ?

**Comment by rollerozxa** [comment]
Packages on ContentDB go through review by an editor before being approved, which mostly consists of checking the licensing of the package. We don't do much of any package curation beyond 2.2 State of Completion, instead users will just use what they want to use whatever they find of use, as you mention.

**Comment by mckaygerhard** [comment]
also why is so rare that only negative threats were leave , intersting..  (first image)

also my improvement over Legen of minecraft were just deleted due "deprecatin".. not all users have the no so friendly recent 5.6.X version .. most older and cheap phones uses multicraft forks as leader engine.. thyat perfects runs my legend of minetest mod that doomed permited to me made some modifications. https://content.minetest.net/packages/D00Med/legendsofminetest/  (second image)

![image](https://user-images.githubusercontent.com/1571724/210253432-3e6e39f8-979f-4085-bbb3-dd03e92c7cd2.png)

![image](https://user-images.githubusercontent.com/1571724/210253874-58e59535-3752-4670-982d-e8c7a8d8ea8f.png)


## Seems there's not so clear rules here? i see old stats ofr LOM and last week was downloaded 3 times

**Comment by rollerozxa** [comment]
Rubenwardy mentioned *reviews*, which are a different kind from regular *threads*. Legend of Minetest still exists on ContentDB as a draft, but unpublished packages have been made inaccessible to non-staff members now.

**Comment by rubenwardy** [comment]
> also why is so rare that only negative threats were leave @rubenwardy , intersting.. (first image) but pssitive ones were removed.. also noted that positive comments were downgraded and all negative comments are from active collaborators

I removed the review but not the thread

> also my improvement over Legen of minecraft were just deleted due "deprecatin".. not all users have the no so friendly recent 5.6.X version .. most older and cheap phones uses multicraft forks as leader engine.. thyat perfects runs my legend of minetest mod that doomed permited to me made some modifications. [content.minetest.net/packages/D00Med/legendsofminetest](https://content.minetest.net/packages/D00Med/legendsofminetest/) (second image)

There was a small bug that was causing a 404. The legendsofminetest package now shows this:

![image](https://user-images.githubusercontent.com/2122943/210260226-8fc737c9-5550-4258-92cc-54cddcd25714.png)

**Comment by mckaygerhard** [comment]
well but why then :

> > also why is so rare that only negative threats were leave @rubenwardy , intersting.. (first image) but pssitive ones were removed.. also noted that positive comments were downgraded and all negative comments are from active collaborators
> 
> I removed the review but not the thread. It's no longer possible to create a review on packages that aren't approved yet

now i can understand why my people always said "i cannot find your package" --- also that is so convenient.. i never take serious the contendb.. i take a time to browse and noted some pretty "not so funny" from the point of view of user.. 

first.. to comment user must registered .. thatr is so not firendly.. its mayor difference with minecraft sites that any user just use phones and can comment no matter of the login.. 

second: noted in the lavastuff the most user level comment has negative points and the comments made by collaborators are not affected.. most comments and reviews that have positive points are made by people from repos or from collaborators.. not by end users.. (umm again is not so transparent)

also well how people can check my package if cannot reviewed?  only "powered conclave" can do?


> 
> ![image](https://user-images.githubusercontent.com/2122943/210260575-a9ceb881-e5a3-40bb-9b32-9768402dcb57.png)
> 
> > also my improvement over Legen of minecraft were just deleted due "deprecatin".. not all users have the no so friendly recent 5.6.X version .. most older and cheap phones uses multicraft forks as leader engine.. thyat perfects runs my legend of minetest mod that doomed permited to me made some modifications. [content.minetest.net/packages/D00Med/legendsofminetest](https://content.minetest.net/packages/D00Med/legendsofminetest/) (second image)
> 
> There was a small bug that was causing a 404. The legendsofminetest package now shows the below. This is part of the changes to how unapproved packages are shown
> 
> ![image](https://user-images.githubusercontent.com/2122943/210260226-8fc737c9-5550-4258-92cc-54cddcd25714.png)

as i know the removal were due "deprecation" that is not a point valid.. the mod is still downloaded since i take some patches and commit to the repo.. again "so convenient" .. 

lest take without burocracy.. people have older devices and older phone.. stop to pollute the options please!
