### ISSUE TITLE
[Feature] Use Git Repository to Replace PostgreSQL Database

### ISSUE THREAD

**Issue by snowyu** [minetest/contentdb#424]
I would like to suggest a new feature for the Minetest contentdb project: replacing the current PostgreSQL database with a Git repository. This would offer several benefits:

1.  Reduce server load: 
  a. No need to deploy a separate database server. 
  b. The entire contentdb project can even be made into a static website, with Git operations moved to the browser side using the [isomorphic-git ](https://isomorphic-git.org/)library.
3.  Quick setup of mirror sites, which will accelerate site access speeds.
4.  Simplify the development of various ContentDB front-end sites, with the Git repository serving as the backend. This would make it easier to create sites with different scenes such as education-based, RPG game-based, puzzle-based, etc.
5.  The proposed Git repository would also allow developers to choose from a variety of comment services, such as [giscus](https://github.com/giscus/giscus), which is based on Github Discussions.
6.  Users can submit new mods and subgames through pull request operations.

The proposed Git repository should have the following directory structure: games, mods, textures, and maps subdirectories.

```
\
|-- games
  |-- minetest_game
    |-- README.md
    |-- screenshot.jpg
|-- mods
  |-- the_mod_or_modPack
    |-- README.md
    |-- screenshot.jpg
|-- textures
|-- maps
```

The configuration instructions should be included in the `README.md` file, and the configuration information should be placed in the [front-matter](https://github.com/snowyu/front-matter-markdown.js) section at the beginning of the `README.md` file. eg,

```md
---
name: the_technical_name
title: human-readable title
description: a short description
type: mod
author:
  - the_author_name
tag:
  - tag1
url: https://the.mod.location.git
screenshot:
  - ./screenshot.jpg
---

## My Minetest Mod

here is the mod detail description
```

* url: the real mod/game/texture package location
  * git location: must end with `.git`
  * zip file location: must end with `.zip`
  * embed package location: must start with './'
* screenshot: the screenshot of the mod/game/texture package. It could be a screenshot or array of screenshots

**Comment by rubenwardy** [comment]
You're welcome to try this as a new project, but ContentDB is designed the way it is for a reason - for user experience. See https://blog.rubenwardy.com/2022/03/24/contentdb/

**Comment by snowyu** [comment]
The better design architecture is to completely decoupling:

1. Index of Contents: The Git repo I designed above is. 
2. Content storage: The actual storage mods, subgame, texture packages can come from git, cloud storage, BT, ...
3. Review/Comment service: There are many clouds or local services to choose from. The Open Source [GISCUS](https://github.com/giscus/giscus) service mentioned earlier is one of them. 
4. Statistics service: too common service.

**Comment by Pantyhose-X** [comment]
> You're welcome to try this as a new project, but ContentDB is designed the way it is for a reason - for user experience. For more information on ContentDB's design, see https://blog.rubenwardy.com/2022/03/24/contentdb/
> 
> For a while, I have been thinking that it would be good to see a cdblite. It wouldn't have much of a web interface, maybe read-only pages for packages at most. No reviews. It would support mirroring other ContentDB servers and adding new packages based on files which could be version controlled
> 
> But ContentDB is designed as it is to give the most value, with reviews and statistics for example

Comment Features: You would say go to Issue Tracker to submit a new feature request or report
The statistics are to get you to take down the mods that no one has downloaded
And two features that are useless to users!

minetest is not better than minecraft except for open source and programming language and decentralization, I don't see where he is better than minecraft

minetest is managed by a part of the core developers, who have no progressive ideas

**Comment by rubenwardy** [comment]
No idea where this is coming from, you don't have to use ContentDB. It already exists, I'm not rewriting it from scratch just for you
