### ISSUE TITLE
Mod similarity search needed before adding a mod

### ISSUE THREAD

**Issue by Desour** [minetest/contentdb#438]
## Problem

I usually search for a modname before using it, to ensure its uniqueness. Normal cdb search however doesn't find mods in modpacks or games.

## Solutions

Add a mod similarity search that can be used before adding a mod.

## Alternatives

Idk.

## Additional context

This is based on a recent experience of mine.

**Comment by rubenwardy** [comment]
You can search for mod names here using ctrl+f. I'll improve search in other ways eventually.  https://content.minetest.net/modnames/
