### ISSUE TITLE
Review voting JS doesn't show removals

### ISSUE THREAD

**Issue by rubenwardy** [minetest/contentdb#474]
## Summary

When clicking to remove a vote, the JS causes the button to still be blue despite the vote being deleted

##### Steps to reproduce

* Click helpful/unhelpful
* Click again. The button is still blue/active, but the vote has been deleted in the database. Can reload to see actual state

**Comment by NA0341** [comment]
I can confirm this behaviour. Was about to report it.
Webbrowser: Vivaldi 6.2.3105.48 on Manjaro (Arch Linux)
