### ISSUE TITLE
Addition of a link to release notes

### ISSUE THREAD

**Issue by dacmot** [minetest/contentdb#480]
## Problem

I think a link to release notes would be a useful and informative addition. Similar to the website, repo, issue tracker and forums' links.

## Solutions

Add a new field to the web form, database, cdb.json parser, and I would recommend displaying a "Changelog" link between "Source" and "Forums", and maybe also next to the "Versions" section.

## Alternatives

Not adding a link?

## Additional context

None.

**Comment by Artisuns** [comment]
I think that's an easy one for me to do as a first contribution

**Comment by Manish-Giri** [comment]
Hi, can I give this a shot?

**Comment by rubenwardy** [comment]
>  @Manish-Giri  Hi, can I give this a shot?

Sure!

Take a look at how "website" is implemented for a guide.

You'll need to:

1. Add a field to the Package table / model
2. Create a migration
3. Add a field to the PackageForm
4. Use that field in logic / package
5. Show it on templates /  packages / view
6. Add to api (done in get dictionary in the package model)

**Comment by Manish-Giri** [comment]
@rubenwardy Thank you for sharing these steps, I'll get started on it!

**Comment by Manish-Giri** [comment]
@rubenwardy I noticed some issues while running the steps in the Getting Started doc. 

The containers that get created after running docker-compose are all named using `-`, while the shell scripts in `utils` seem to look for containers that are named using `_`. Here are some screenshots -

1. Here are some of the running containers after running ` docker-compose up --build`. Notice the name - `contentdb-app-1` -
<img width="184" alt="Screen Shot 2023-10-18 at 9 05 29 PM" src="https://github.com/minetest/contentdb/assets/11348778/945cd882-7150-40ff-9f9d-de901c75bffa">

2. The `run_migration.sh` script looks for a container called `contentdb_app_1`, which doesn't exist and so the command fails -
<img width="884" alt="Screen Shot 2023-10-18 at 9 09 15 PM" src="https://github.com/minetest/contentdb/assets/11348778/8d74a378-4c85-4c5a-a548-52b622b8aac1">

**Comment by Manish-Giri** [comment]
I think it's failing in Step 2 now

<img width="540" alt="Screen Shot 2023-10-18 at 10 09 15 PM" src="https://github.com/minetest/contentdb/assets/11348778/19e2263b-716d-4e53-a03b-845c8131c025">

**Comment by rubenwardy** [comment]
Yeah, if you're using a newer version of docker-compose you need to use - and not _

**Comment by rubenwardy** [comment]
Note, as of https://github.com/minetest/contentdb/commit/4ef3aae193ddf5f2564c87a1ddb0d79037d784b9 the `-` vs `_` issue is fixed

**Comment by Manish-Giri** [comment]
Thank you, I'll get back on this

**Comment by dacmot** [comment]
Just wanted to say thank you @Manish-Giri ! The new release notes panel looks great!
