### ISSUE TITLE
convert locales from a session/cookie to individual directories

### ISSUE THREAD

**Issue by recluse4615** [minetest/contentdb#485]
when working with multilingual sites, it's generally recommended for SEO purposes to:
- define the language inside the markup
- include the language/locale in the url (eg: `https://content.minetest.net/en-us/` vs `https://content.minetest.net/`)
- (optionally - need to confirm) use `hreflang` on canonical urls to denote different translated versions of the page

problems:
- package pages: UGC is not translated in to multiple languages, how can we deal with this?
- flat pages: these also aren't translated

this might be something that's either impossible to do or very difficult, but would be ideal in the long term

**Comment by rubenwardy** [comment]
This requires package meta translation, which requires that the engine support it first ( https://github.com/minetest/minetest/pull/12208 )

**Comment by rubenwardy** [comment]
Engine support has been merged, which means that this issue is now waiting on #516

**Comment by rubenwardy** [comment]
closing for now, this would be quite disruptive for such a low % of translated packages. Can be reconsidered when more packages support translation
