### ISSUE TITLE
support filtering mods by supported game(s)

### ISSUE THREAD

**Issue by programmerjake** [minetest/contentdb#488]
## Problem

I would like to be able to look through the mod list without having to manually filter out mods that are incompatible with the game I selected

## Solutions

Add a way for the mod list to be filterable by supported game(s)

## Alternatives

Do nothing...which makes contentdb very annoying to use when trying to find mods for the game I'm using.

**Comment by rubenwardy** [comment]
This is the repository for the https://content.minetest.net/ website

On the ContentDB interface, this is already possible by going to the "hub" page of a game. For example: https://content.minetest.net/packages/Warr1024/nodecore/hub/

I suspect you meant to file this on the engine. In which case, this is a duplicate of #13851

**Comment by programmerjake** [comment]
> On the ContentDB interface, this is already possible by going to the "hub" page of a game. For example: https://content.minetest.net/packages/Warr1024/nodecore/hub/

ah, I never noticed that button until now...
