### ISSUE TITLE
No ability to fetch the "source" URL through the API?

### ISSUE THREAD

**Issue by FloraMaeWolfe** [minetest/contentdb#490]
Either I'm overlooking it, or I'm an idiot, but I can't seem to find a way to use the API to fetch the "Source" URL of projects on contentdb.

Is this feature available? If so, could someone point it out for me? If not, could this be added as a feature?

I want to be able to use bash scripting to obtain the source code URL of projects on the contentdb for various purposes.

Thank you.

**Comment by rubenwardy** [comment]
This is "repo" in https://content.minetest.net/api/packages/Warr1024/nodecore/

**Comment by FloraMaeWolfe** [comment]
Thank you so much for pointing this out, I guess I overlooked it.
