### ISSUE TITLE
Make release titles longer

### ISSUE THREAD

**Issue by Zughy** [minetest/contentdb#492]
## Problem
Sometimes my release titles don't fit the title field because of their length (e.g. https://gitlab.com/zughy-friends-minetest/parties/-/releases/2.1.0)

## Solutions

Increase the length of the field

**Comment by rubenwardy** [comment]
The intent of the release title is currently to hold names like "2.1.0"

I think I should probably have two fields here - a short one (like current) for "2.1.0" and a longer one for a human-readable flair name
