### ISSUE TITLE
OAuth callback enforces https://

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest/contentdb#498]
## Summary
I'm currently developing an application locally and tried to add an OAuth App with a callback-url to localhost without TLS.

The redirect from the CDB always redirects me to the TLS-enabled site (https://localhost:8080/... in my case) which wont work.

My current workaround is to just remove the additional "s" in the browser-bar and continue but it would be nice if i could develop locally without that.

##### Steps to reproduce
* Use a redirect-url with plain HTTP

(Side-note: aside from that i haven't seen any other issues with the OAuth flow, good job :+1: OIDC would be nice to have but one thing at a time :wink:)

**Comment by rubenwardy** [comment]
I suspect this is being done by nginx and not ContentDB, which is why I didn't catch this in testing. The config has: `proxy_redirect http:// https://;`

**Comment by rubenwardy** [comment]
I've removed this from my nginx config, please retest

**Comment by BuckarooBanzay** [comment]
nice, works :tada: thanks
