### ISSUE TITLE
make featured status in client more obvious

### ISSUE THREAD

**Issue by wsor4035** [minetest/contentdb#500]
## Problem

(reporting from matrix)
featured status in the minetest client isnt clear enough

## Solutions

add `[featured]` to package title (suggested by roller)

## Alternatives

🤷 

## Additional context

line of code that currently does it: https://github.com/minetest/contentdb/blob/36c63b46577a2198a2bc389b846b57d810793fe4/app/blueprints/api/endpoints.py#L90

**Comment by ancientmarinerdev** [comment]
It is worth considering changing background colour also, to help differentiate at a visual glance.

**Comment by rubenwardy** [comment]
I originally put this in the title, but found that it clipped on larger font sizes / smaller displays. The description wraps at least

> It is worth considering changing background colour also, to help differentiate at a visual glance.

We can only change the screenshot, description, and title from the server-side. Other changes would need to be done on the engine, at which point I'd rather wait for the redesign

**Comment by rubenwardy** [comment]
I'm wondering if I can include colorize codes in the API response, or if Minetest will strip that out. If it's respected then we could give the featured label a different color

**Comment by rubenwardy** [comment]
Solved by https://github.com/minetest/contentdb/commit/465370d3fc433b1ae050090ad3e85196b610d6fc and https://github.com/minetest/minetest/pull/14510
