### ISSUE TITLE
Some petitions now MTG is not the main game

### ISSUE THREAD

**Issue by runsy** [minetest/contentdb#502]
- Remove 'Modname Uniqueness': Gaming is now king, that a game decides to take over mod names is possible. This would prevent using the 'original' mod and only use the in-game mod.
- Mod veto: Mods that you simply do not want to be installed in the game.
- Only positive votes: As in Youtube, only see positive votes. Negative votes and comments are the devil's work, they are not fair, Youtube says so.
- Community Pictures: Let fans of the game upload their favorite screenshots.

**Comment by rubenwardy** [comment]
Only feature I support here is the community pictures, but that's covered by #318

Closing as won't add
