### ISSUE TITLE
.jpeg files fail to make thumbnails while .jpg work

### ISSUE THREAD

**Issue by wsor4035** [minetest/contentdb#505]
## Summary
see title, cc @rollerozxa @Montandalar

##### Steps to reproduce
try uploading a .jpeg file and look at thumbnails

**Comment by Montandalar** [comment]
Found another one in the wild
https://content.minetest.net/packages/Starbeamrainbowlabs/worldeditadditions/
Image No. 5 "A scene showing off lots of commands"
