### ISSUE TITLE
Is there a way to translate mods / games descriptions?

### ISSUE THREAD

**Issue by megustanlosfrijoles** [minetest/contentdb#507]
## Problem

I want to know if there is a way to translate a mod / game description. Currently the website supports translations, but the descriptions of the content itself are mostly in English. It would be very helpful for users  to have a small description of what they're installing. I'd make the website more user friendly / accessible.

Please let me know if there is already a way to do this.

**Comment by rubenwardy** [comment]
This is a planned feature and is waiting for the following engine PR to be accepted: https://github.com/minetest/minetest/pull/12208
