### ISSUE TITLE
[Feature] Add source/repo link to output packages api

### ISSUE THREAD

**Issue by Miniontoby** [minetest/contentdb#514]
## Problem

It is not possible to get only the source/repo link in the output of the `/api/packages/` output. 

I am making a script which would allow me to download mods using the github repo. Right now it just checks every known minetest user their github and checks if the modname is in there, but this is absolutely not efficient!

And at the moment I am unable to just get the source/repo link from the `/api/packages/` path, without getting the rest of the fields which is not efficient, since I only need the author and repo link.

## Solutions

The solution could be to add a new `/api/packages/?fmt=` type to the API, maybe called `source`

## Alternatives

An alternative solution, which might even be better, would be to add an option like `?include_fields=` where you can provide a using `+` joined list of fields. (e.g. `?include_fields=author+name+source`)

**Comment by rubenwardy** [comment]
https://content.minetest.net/api/packages/?fmt=vcs
