### ISSUE TITLE
Allow translators to write strings for each package type if necessary

### ISSUE THREAD

**Issue by rollerozxa** [minetest/contentdb#538]
In some places in the translations `%(type)s` is used as a format placeholder to switch out for each package type, which works well in English as all of them are preceded with "a", but does not work as well for other languages where nouns have classes/genders.

For example the source string "%(display_name)s has a %(type)s placed at #%(place)d.", translated into Swedish:

![image](https://github.com/minetest/contentdb/assets/60856959/e8744624-4d73-45c2-b6b2-f7d1783b47b0)

The correct strings in Swedish for each package type would be:
- "%(display_name)s har ett spel placerat på #%(place)d"
- "%(display_name)s har en modd placerat på #%(place)d"
- "%(display_name)s har ett texturpaket placerat på #%(place)d"

With "ett"/"en" for referring to the nouns fluctuating for each type, but when it is combined into one it's not possible to get it right every time without working around the grammar rules with overly verbose wording.

Some strings like "To provide translations for your %(type)s, you need to create .tr files and upload a new release." and "To provide translations for your %(type)s, you need to create .tr files and upload a new release." could be genericised to simply call it a package instead of the package type.

**Comment by rubenwardy** [comment]
There's a lot of places that use the package type. Ideally, I'd like to be able to tell babel/gettext that type is an enum with 3 possible values so that it can expand out the substitution during extraction time

**Comment by rollerozxa** [comment]
> Ideally, I'd like to be able to tell babel/gettext that type is an enum with 3 possible values so that it can expand out the substitution during extraction time

Yeah it feels like something that would come up quite often when it comes to doing translations that gettext would have a more elegant way of handling. But splitting up the strings works fine for being able to translate it more grammatically correct, thank you! :D
