### ISSUE TITLE
Broken link in tags editor

### ISSUE THREAD

**Issue by Wuzzy2** [minetest/contentdb#543]
In the tags editor (<https://content.minetest.net/tags/>), there is a link but it is broken:

> Also see Package Tags.

The link is on the words "Package Tags" and leads to <https://content.minetest.net/help/package_tags/> but this gives me a "Not Found" error.

**Comment by rubenwardy** [comment]
This page was deleted when tags got support for descriptions, as it was no longer needed. Removed the link
