### ISSUE TITLE
[Collection of Issues]: Layout Issues (overflowing elements)

### ISSUE THREAD

**Issue by NA0341** [minetest/contentdb#551]
## Introduction

This issue is to collect and fix issues related to page layout.
Individual cases can be checked off by checkboxes.
Please feel free to edit this issue in order to extend or improve it.

## Layout Issue List

+ [x] Compatible Games Category is overflowing (displaying over below content) on https://content.minetest.net/packages/GreenXenith/hexagonal/

**Comment by rubenwardy** [comment]
What browser are you using? It's supposed to have a limited height with a scrollbar like so:

![image](https://github.com/user-attachments/assets/fdb3c518-d6ab-49a0-9cde-dd8e11ec27c8)

**Comment by NA0341** [comment]
I use Vivaldi.
Just checked and it's working fine now.
