### ISSUE TITLE
ContentDB API returns previously featured packages instead of currently featured

### ISSUE THREAD

**Issue by ryvnf** [minetest/contentdb#553]
## Summary

I noticed that the featured packages were rotated on the ContentDB home page. Now its "Age of Mending", "Phonograph" and "Airship". Previously it was "The Velvet Crystal", "Citadel", "Unexpected Gambit" and "Pride Flags". In the Minetest client however the previously featured packages are still listed as the currently featured ones.

It appears like the ContentDB API still returns the old featured packages as featured instead of the new ones.

##### Steps to reproduce
It can currently be reproduced by going to https://content.minetest.net/api/packages

The old featured packages are still listed as currently featured. The newly featured packages are not listed as featured.

**Comment by rollerozxa** [comment]
I believe this is simply due to that one uses the Featured collection and one uses the Spotlight collection when highlighting packages.
