### ISSUE TITLE
License select text is nearly unreadable

### ISSUE THREAD

**Issue by adrido** [minetest/contentdb#74]
![grafik](https://user-images.githubusercontent.com/3142688/40572527-e1dff996-60ae-11e8-9399-7c3b3c538444.png)

PS: great work!

**Comment by rubenwardy** [comment]
What browser do you use?

**Comment by adrido** [comment]
Firefox 60.01

**Comment by Ezhh** [comment]
I have the same issue on Chrome (I mentioned it to you previously). It's all dropdowns, not just license.

**Comment by 4w** [comment]
Confirmed in Chromium 66.0.3359.181
