### ISSUE TITLE
Add video field

### ISSUE THREAD

**Issue by NathanSalapat** [minetest/contentdb#75]
Have you thought of adding an option where you could put a video URL for the mod. It could be nice if people recorded mod review videos of their mods to include a link to that video on the mods page.

**Comment by rubenwardy** [comment]
There's not likely to ever be support for that in Minetest, I suggest just putting a link in the long description (it supports markdown)

**Comment by NathanSalapat** [comment]
Ah, that works too. I hadn't thought of that.

**Comment by rubenwardy** [comment]
Steps:

- Add column to Package.
- Run `./utils/create_migration.sh`.
- Check migration, make sure `server_default` exists.
- Optionally edit it, and run `./utils/reload.sh`.
- Run `./utils/run_migration.sh`.
- Add field to PackageForm in `blueprints/packages/packages.py`, make sure to include a URL validator.
- Add field to `templates/packages/create_edit.html`.
- Update `templates/packages/view.sh` to use the field.
- Test

**Comment by rubenwardy** [comment]
This should be implemented by changing PackageScreenshot to PackageMediaItem, and adding video types.

**Comment by rubenwardy** [comment]
Implemented. See Package > Edit > Video URL
