### ISSUE TITLE
Tags request thread

### ISSUE THREAD

**Issue by ClobberXD** [minetest/contentdb#85]
## Proposed tags
- [ ] server-side
- [ ] moderation

##### This is an incomplete list, I'll keep adding to it as I come up with more...

**Comment by rubenwardy** [comment]
Server-side doesn't make sense, all mods are server-side
Moderation is under maintenance.

Take a look at  https://content.minetest.net/help/package_tags/

**Comment by ClobberXD** [comment]
Oh, the `maintenance` tag is what I'm looking for... thanks!
