### ISSUE TITLE
Bug - Username needs to be in lowercase in sign-in page

### ISSUE THREAD

**Issue by ClobberXD** [minetest/contentdb#89]
e.g. `ClobberXD` throws an error, while `clobberxd` does not.

**Comment by rubenwardy** [comment]
Username/password isn't really supported yet

**Comment by ClobberXD** [comment]
How do you sign in then?

**Comment by rubenwardy** [comment]
Github

**Comment by ClobberXD** [comment]
That's what I meant :)

But entering ClobberXD (my Github username), throws an error stating "incorrect username and/or password". `clobberxd` worked perfectly fine, though...

**Comment by rubenwardy** [comment]
Click the github link, don't enter your details there

**Comment by ClobberXD** [comment]
Oh! It works now, thanks. You might also want to disable (grey-out) the username and password fields until they work properly. That way, new users won't get confused...
