### ISSUE TITLE
In-game online content browser too cramped

### ISSUE THREAD

**Issue by ClobberXD** [minetest/contentdb#90]
![image](https://user-images.githubusercontent.com/36130650/40650136-2fc230c2-6350-11e8-9e3a-5976e1f91d0c.png)

Either the number of packages per page could be reduced to 4, or the in-game content browser formspec could be made larger (recommended).

A character limit could be set to the package's short description to prevent huge "short" descriptions, and subsequently eliminate the need for scroll-bars.

**Comment by rubenwardy** [comment]
Wrong repo

**Comment by ClobberXD** [comment]
Elaborate please... :confused:

**Comment by ClobberXD** [comment]
Apologies...
