### ISSUE TITLE
Content browser does not retrieve any packages from ContentDB

### ISSUE THREAD

**Issue by ClobberXD** [minetest/contentdb#96]
Error message returned:
`ERROR[Main]: https://content.minetest.net/packages/ not found (Timeout was reached) (response code 200)`
![image](https://user-images.githubusercontent.com/36130650/41393481-a8983116-6fc3-11e8-905c-8166fcd7a301.png)

**Comment by ClobberXD** [comment]
Issue persists. Re-open please.

**Comment by rubenwardy** [comment]
Wrong repo

**Comment by ClobberXD** [comment]
Wait... you told me to open the issue here when I first opened it on `minetest/minetest`...

**Comment by rubenwardy** [comment]
because I thought the issue was here, but it's not
